CREATE TABLE `movie` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '电影id',
	`MOVIE_NAME` VARCHAR(256) NULL DEFAULT NULL COMMENT '电影名字' COLLATE 'utf8_unicode_ci',
	`REST_NUM` INT(11) NOT NULL COMMENT '剩余票数',
	`ADD_TIME` DATETIME NULL DEFAULT NULL COMMENT '添加时间',
	`START_TIME` DATETIME NULL DEFAULT NULL COMMENT '开始时间',
	`END_TIME` DATETIME NULL DEFAULT NULL COMMENT '结束时间',
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
