CREATE TABLE `user` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '用户id',
	`NAME` VARCHAR(256) NULL DEFAULT NULL COMMENT '用户姓名' COLLATE 'utf8_unicode_ci',
	`PASSWORD` VARCHAR(16) NULL DEFAULT NULL COMMENT '用户密码' COLLATE 'utf8_unicode_ci',
	`EMAIL` VARCHAR(30) NULL DEFAULT NULL COMMENT '用户email' COLLATE 'utf8_unicode_ci',
	PRIMARY KEY (`ID`)
)
COMMENT='用户表'
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
